[platformio]
default_envs = esp32dev
src_dir = .
test_dir = tests/unit

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<src/> +<app/> +<core/> +<domain/> +<adapters/> +<platform/> +<services/>
build_flags = 
    -std=c++17
    -Iinclude
    -I.

[env:native]
platform = native
test_build_src = true
build_src_filter = -<*> +<core/> +<domain/> +<adapters/> +<platform/> +<services/>
build_flags = 
    -std=c++17
    -D UNIT_TEST
    -Iinclude
    -I.

